const images = {
  bank: {
    ansar: require('../assets/images/bank/ansar.png'),
    day: require('../assets/images/bank/day.png'),
    eghtesad: require('../assets/images/bank/eghtesad.png'),
    karafarin: require('../assets/images/bank/karafarin.png'),
    keshvarzi: require('../assets/images/bank/keshvarzi.png'),
    maskan: require('../assets/images/bank/maskan.png'),
    mehr: require('../assets/images/bank/mehr.png'),
    meli: require('../assets/images/bank/meli.png'),
    mellat: require('../assets/images/bank/mellat.png'),
    parsian: require('../assets/images/bank/parsian.png'),
    pasar: require('../assets/images/bank/pasar.png'),
    post: require('../assets/images/bank/post.png'),
    refah: require('../assets/images/bank/refah.png'),
    saman: require('../assets/images/bank/saman.png'),
    sanaat: require('../assets/images/bank/sanaat.png'),
    sarmaye: require('../assets/images/bank/sarmaye.png'),
    saderat: require('../assets/images/bank/sedarat.png'),
    sepah: require('../assets/images/bank/sepah.png'),
    shahr: require('../assets/images/bank/shahr.png'),
    sina: require('../assets/images/bank/sina.png'),
    taavon: require('../assets/images/bank/taavon.png'),
    tat: require('../assets/images/bank/tat.png'),
    tejarat: require('../assets/images/bank/tejarat.png'),
    tosee: require('../assets/images/bank/tosee.png'),
  },
  global: {
    delete: require('../assets/images/global/delete.png'),
    no_pic: require('../assets/images/global/no_pic.png'),
    arrow_down: require('../assets/images/global/arrow_down.png'),
    calender: require('../assets/images/global/calendar.png'),
    search: require('../assets/images/global/search.png'),
    phone: require('../assets/images/global/phone.png'),
    key: require('../assets/images/global/key.png'),
    arrow_back: require('../assets/images/global/arrow_back.png'),
    arrow_right: require('../assets/images/global/arrow_right.png'),
    logo: require('../assets/images/global/Jimbo.png'),
  },
  tab: {
    bars: require('../assets/images/tab/bars_chart.png'),
    profile: require('../assets/images/tab/profile.png'),
    transfer: require('../assets/images/tab/transfer.png'),
    weblog: require('../assets/images/tab/weblog.png'),
  },
  button: {
    GreenBtn: require('../assets/images/Button/button.png'),
    GreenBtn2: require('../assets/images/Button/largeButton.png'),
    redBtn: require('../assets/images/Button/redBtn.png'),
  },
  example: {
    bit: require('../assets/images/example/bit.png'),
    pm: require('../assets/images/example/pm.png'),
    web2: require('../assets/images/example/web2.png'),
    bitcoinC: require('../assets/images/example/bitcoinC.webp'),
    dash: require('../assets/images/example/dash.webp'),
    ethereum: require('../assets/images/example/ethereum.webp'),
    litecoin: require('../assets/images/example/litecoin.webp'),
    tether: require('../assets/images/example/tether.webp'),
    tron: require('../assets/images/example/tron.webp'),
    xrp: require('../assets/images/example/xrp.webp'),
    Rial: require('../assets/images/example/Rial.png'),
    zcash: require('../assets/images/example/zcash.png'),
    monro: require('../assets/images/example/monro.png'),
    doge: require('../assets/images/example/doge.png'),
  },
  login: {
    dates: require('../assets/images/login/dates.png'),
    eye: require('../assets/images/login/eye.png'),
    mail: require('../assets/images/login/mail.png'),
    males: require('../assets/images/login/males.png'),
    phone: require('../assets/images/login/phone.png'),
    lock: require('../assets/images/login/lock.png'),
  },
};
export default images;
