import Tab1 from './Tab1';
import Tab2 from './Tab2';
import Tab3 from './Tab3';
import Tab4 from './Tab4';
import Tab5 from './Tab5';
export const Hesab = Tab1;
export const Bank = Tab2;
export const Sheba = Tab3;
export const Wallet = Tab4;
export const Auth = Tab5;
