import ProfileScreen from './ProfileScreen';
import BuyingScreen from './BuyingScreen';
import WeblogScreen from './WeblogScreen';
import PricesScreen from './PricesScreen';
import SplashScreen from './SplashScreen';
import LoginScreen from './LoginScreen';
import SignInScreen from './SignInScreen';
import PayingScreen from './PayingScreen';
import WeblogDetailScreen from './WeblogDetailScreen';
import ForgotPassScreen from './ForgotPassScreen';
import PayScreen from './PayScreen';
import ArzScreen from './ArzScreen';
import Arz2Screen from './Arz2Screen';
export const Arz = ArzScreen;
export const Arz2 = Arz2Screen;
export const Pay = PayScreen;
export const ForgotPass = ForgotPassScreen;
export const Prices = PricesScreen;
export const Paying = PayingScreen;
export const Profile = ProfileScreen;
export const Buying = BuyingScreen;
export const Weblog = WeblogScreen;
export const Splash = SplashScreen;
export const Login = LoginScreen;
export const SignIn = SignInScreen;
export const WeblogDetail = WeblogDetailScreen;
